name: 'SchemaCrawler Action for GitHub Actions'
author: 'Sualeh Fatehi'
description: 'Run a SchemaCrawler command in the build pipeline'

branding:
  icon: 'database'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'

outputs:
  exit_status:
    description: 'Exit status of the SchemaCrawler command-line run'
